FROM hoagnetwork/ffmpeg:1.0

COPY images images

ENTRYPOINT ffmpeg -i images/hoag_music.png -i http://audio.exmaple.stream.com -acodec libmp3lame -ab "128k" -ac 2 -ar 44100 -f flv rtmp://stream.hoag.network/live/
