name: Built

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test build Image
        run: bash scripts/build.sh
        env:
          NAME: latest
